version: '3.6'

services:
  ui:
    image: node:16-alpine3.11
    command: npm run dev
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - api
    environment:
      HOST: '0.0.0.0'

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    ports:
      - 8000:80
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env
    
  db:
    image: postgres:13.3-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 15432:5432

volumes:
  node_modules:
  db:
