name: CI

on: [push, pull_request]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup local vars
  #       run: cp .env.sample .env

      # - name: Run tests
      #   run: ./test.sh
  build:
    # needs: test
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_REPOSITORY: 'pyritewolf/tattoo-socials'
    steps:
      - uses: actions/checkout@v2

      - name: Build image & push to Docker Hub
        run: ./build.sh
